version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: notes-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: notes
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: notes
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_URL: jdbc:mariadb://db:3306/notes
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_data:
